@echo off
echo Compilando o projeto...
javac -d bin -sourcepath src\main\java src\main\java\com\gpon\view\InterfaceGrafica.java
echo Iniciando a Calculadora GPON...
java -cp bin com.gpon.view.InterfaceGrafica
